### ISSUE TITLE
Provide GM_info

### ISSUE THREAD

**Issue by johnd0e** [HubertZhang/IITC-Mobile#1]
It's needed for `About IITC`, where all plugins listed.

AFAIK every other known userscripts manager provides `GM_info`.

**Comment by HubertZhang** [comment]
This has been implemented, please check

https://github.com/HubertZhang/IITC-Mobile/blob/203676b54b96bfb354af557604a42435ed4efaea/BaseFramework/ScriptsManager/Script.swift#L44

**Comment by johnd0e** [comment]
Good to know!
Could you specify sample content of GM_info?
