### ISSUE TITLE
Tried to join instagram group

### ISSUE THREAD

**Issue by uhlhosting** [HubertZhang/IITC-Mobile#2]
Got banned when tried to join instagram group. I need more details about how iitc can handle the new features of discovering all visited and not visited portals.

**Comment by HubertZhang** [comment]
Sorry for late reply, but there is no instagram group for IITC-Mobile(iOS)..

AFAIK, this feature is supported by IITC-CE's plugin. You can try it in testflight version of IITC-Mobile on iOS or visit [iitc.app](iitc.app) for Android and Desktop version
