### ISSUE TITLE
iOS app bottom padding

### ISSUE THREAD

**Issue by Jo0Lz** [HubertZhang/IITC-Mobile#5]
Is it possible to have extra padding on the bottom to have the bottom bar easily accessible? Right now, the task switcher “line” is constantly in the way. 

If someone has a plug-in that accomplishes this, I’d also be happy to install it.

**Comment by Jo0Lz** [comment]
Never mind, I fixed it by adding 20px bottom padding to '#updatestatus'. Thanks.

**Comment by virtualvoid** [comment]
well, how did you achieved that ? i have fat fingers and most of the time i’m unable to open up portal details.
